name: WaveCam
options:
  bundleIdPrefix: com.stonezone
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
settings:
  base:
    MARKETING_VERSION: "0.1"
    CURRENT_PROJECT_VERSION: "9"
    DEVELOPMENT_TEAM: "78725QX6PZ"
    CODE_SIGN_STYLE: Automatic
    GENERATE_INFOPLIST_FILE: NO
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "1"
targets:
  WaveCam:
    type: application
    platform: iOS
    sources:
      - Sources
      - Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.stonezone.WaveCam
        INFOPLIST_FILE: Info.plist
